'use strict';

module.exports = {
    /**
     * When editing your questions pay attention to your punctuation. Make sure you use question marks or periods.
     * Make sure the first answer is the correct one. Set at least ANSWER_COUNT answers, any extras will be shuffled in.
     */
    "EXERCISES_EN_US" : [
        "Squats, make sure to have your heels anchored to the ground, bend at the hips, chest up and get your butt down at least as parallel to the ground and ideally lower",
        "Push ups, good old fashion, high quality, not too fast and not too slow, pushups. Just like racing was in the good old days, minus the unsafe cars, crashes and dying and what-not",
        "Running in place with high knees.  Why? Because as long as I am on the track, you won't be in the running for the lead so you better like this type of running",
        "Running in place with normal height knees",
        "Forward lunge, alternating legs, kind of like you're coming at a bro but then think better of it but then you're coming at a bro again but with the other leg",
        "Jumping Jacks, this is for when your car breaks down mid-race and all you can do is cheer me on from the grandstands",
        "Abdominal crunch, fifteen repititions",
        "Leg raises, fifteen repititions",
        "Backwards lunge with alternating legs, kind of like when a bro is coming at you and you are retreating with one leg but then you're like, did they just disrespect my significant other like that? and you're like oh no and you come back but then you realize they are jacked up on mountain dew, chip and you retreat again, with the other leg",
        "High plank, hold for thirty seconds. Yes, this is just the basic good old high plank.  Enjoy this beautiful simplicity while it lasts.",
        "Low plank, hold for thirty seconds. Yes, this is just the basic good old low plank.  Enjoy this beautiful simplicity while it lasts.",
        "Side plank, left side, hold for thirty seconds",
        "Side plank, right side, hold for thirty seconds",
        "On the floor, scissor kicks, do as many as you can in thirty seconds",
        "High plank jacks, it's like a jumping jack but in the plank position",
        "Tuck jumps, where you jump up high in the air and tuck your knees under your chest",
        "Russian twist, this an ab exercise, not a drink",
        "Knee tuck crunches, we need to get that belly out of the way for the steering wheel",
        "Jabs, alternating fists. This is for fast hands, so punch hard and fast",
        "Jabs, right fist only. This is for quick and clean gear changes if you're in right-hand driving countries.  This is for no use at all, if you're in left-hand driving countries.  Weirdos",
        "Jabs, left fist only. This is for quick and clean gear changes if you're in left-hand driving countries.  Wait, why are you shifting with your left hand?  I thought that only happened in that Tokyo Drift movie, when that Nascar kid got lost in Japan",
        "Upper cuts, right fist only. Punch through the target and hard",
        "Upper cuts, left fist only. Punch through the target and hard",
        "Jab and cross, a combination of punches. Jab with your right hand and cross with your left. Visualize your nemisis right in front of you and knock them out, like we know you will on the last lap of the race",
        "Jump an invisible rope, this is for quick feet on and off the pedals",
        "Jump an invisible rope with just your left foot. This is for left foot braking but who are we kidding, you're scared of that. haha",
        "Jump an invisible rope with just your right foot. This is to help you get back on throttle faster. We watched your tape. <break time=\"3s\" />. Those three seconds weren't a break for you, that's how long it takes you get back on throttle",
        "Jump an invisible rope with just your left foot. This is to help you get drop the clutch super fast for all those drifter, side ways, burn up tires and go slow things you know you secretly dream of doing.  You disgust me",
        "Alligator push ups, the kind where you alternate bringing your knee to your elbow when you go down on a push up.  Who are we kidding, you're having a stuffed alligator do push ups right now, aren't you?",
        "Jump squats.  It's like a regular squate except you jump when you come back up.  Try to get into a rythm so you don't need to reset your feet each time",
        "Mountain climbers, this is where you stand in place and pretent to be climbing a mountain by bringing your knees up and reach up to pull yourself up a rock climbing wall as fast as you can or you just look like an idiot who doesn't know how to run and is simultaneously trying to claw someones eyes out",
        "Wall sit, now don't be a cheater. Make sure your thighs are parallel to the ground",
        "Burpees, on yeah baby. No we're cooking with propane! Do as many high quality burpess as you can",
        "High plank, knee to elbow. Get in a high plank position and then alternate bringing your right knee, to your right elbow.  Then your left knee, to your left elbow.  Stop arching your back, I can see that.  Well, not really",
        "Tricep dip.  You can do this on the floor or you can find a chair and use the chair to work on your triceps. Remember, if you want to be rocking a gun show, most of the gun is in the triceps, not the biceps",
        "Up downs, whoo! that six pack of coors you had last night is about to make a comeback! In a standing position, drop to the push up position and then jump back up to the standing position.  Do the pushup for extra points that will not count towards the chase",
        "Clapping push ups! That's right, push up with explosive power, like you removed the restrictor plate, power.  And while in the air, clap your hands and catch yourself before you have a mouthful of floor sandwich.  If you can't do a clap push up, practice just doing an explosive push up without the clap",
        "Speed push ups.  Tuck your elbows next to your body and with a full range of motion, do push ups as fast as you can. Your elbows don't need to lock out but make sure to have that full range of motion or else you will not pass tech inspection",
        "High plank to low plank.  Start in a high plank and one arm at a time, transition to a low plank and then back again.",
        "High plank, knee crosses.  Get into a high plank position and then bring your right knee, to your left elbow.  Then your left knee, to your right elbow.  Keep alternating",
        "Star jacks, start in a crouched down position and then explode up to do a jumping jack in the air. It's like an explosive jumping jack. Right here, right now you are the star, shining bright and even brighter than Tom Cruise",
        "Lazy eights, you're welcome, you get to breathe.  Put your right hand in the dumbs up position. Put your hand out in front of your face and now move your thumb around as if you were drawing a side-ways eight or an infinity symbol. While keeping your head completely still, follow your thumb movement with your eyes.  Stop questioning me and just do it.  I am Yoda, you are Jar Jar Binks and no, he is not the ultimate emperor",
        "Cross crawls, in a standing position, bring your knees up like you were doing high knees and when a knee is up, touch that knee with the opposite hand. Right knee up, touch with left hand. Left knee up, touch with right hand. This is a great pre-race warm up but, what do you care, you piss excellence, right?",
        "Jump rope, with an invisible rope, five jumps on the right foot only and then five jumps on the left foot only. Alternate feet every five feet and focus on having your feet touch the floor for the least amount of time possible",
        "Imaginary box drill, clockwise with two feet. Pretend there is a box under your feet. Jump with both feet from one corner of the box, to another corner of the box in a clockwise pattern.  Each jump should be about two feet",
        "Imaginary box drill, counter-clockwise with two feet. Pretend there is a box under your feet. Jump with both feet from one corner of the box, to another corner of the box in a counter-clockwise pattern.  Each jump should be about two feet",
        "Imaginary box drill, clockwise with your right foot only. Pretend there is a box under your feet. Jump with your right foot only from one corner of the box, to another corner of the box in a clockwise pattern.  Each jump should be no more than two feet",
        "Imaginary box drill, clockwise with your left foot only. Pretend there is a box under your feet. Jump with your left foot only from one corner of the box, to another corner of the box in a clockwise pattern.  Each jump should be no more than two feet",
        "Imaginary box drill, counter-clockwise with your right foot only. Pretend there is a box under your feet. Jump with your right foot only from one corner of the box, to another corner of the box in a counter-clockwise pattern.  Each jump should be no more than two feet",
        "Imaginary box drill, counter-clockwise with your left foot only. Pretend there is a box under your feet. Jump with your left foot only from one corner of the box, to another corner of the box in a counter-clockwise pattern.  Each jump should be no more than two feet",
        "Imaginary rope jump drill, forward and backwards with both feet. Stand with your feet together and pretent there is an imaginary rope in front of your feet. Jump over that rope forwards and then backwards, as fast as you can, while maintaining control and good form",
        "Imaginary rope jump drill, forward and backwards with your right foot only. Stand with your right foot only and pretent there is an imaginary rope in front of your foot. Jump over that rope forwards and then backwards, as fast as you can, while maintaining control and good form",
        "Imaginary rope jump drill, forward and backwards with your left foot only. Stand with your left foot only and pretent there is an imaginary rope in front of your foot. Jump over that rope forwards and then backwards, as fast as you can, while maintaining control and good form",
        "Alternating lunge jumps.  Start in a lunge position with one leg extended out in front of the other and explosively jump up and while in the air, alternate your legs so you land with the other foot up",
        "Single leg dead lift with your left leg.  Time to break some power lifting records! With your right leg up in the air, slowly and with stablity bend at your knee and hips to reach down in front of yourself and touch the floor, with your right hand and then come back up.  And repeat",
        "Single leg dead lift with your right leg.  Time to break some power lifting records! With your left leg up in the air, slowly and with stablity bend at your knee and hips to reach down in front of yourself and touch the floor, with your left hand and then come back up.  And repeat",
        "Spider lunges. Put down the mountain dew and get in a high plank position. Bring your left foot up to be just outside your left hand. Hold for a second and then bring it back to the original high plank position.  Now do the same with your right leg.  Keep alternating",
        "Plank tap. Get into a high plank position, take your left hand and tap your right shoulder, while maintaining your perfect plank position. Bring your hand back down and do the same with your right hand. Alternate tapping your shoulders and now you'll have something to do with your hands when you get that first post-race victory interview by the Forest Grove High School bi-weekly journal",
        "Side lunge, alternating sides.  Start in a standing position with both feet together, hold your hands together, near your chest together. In one smooth movement, lunge to your right side, touch your right eblow to your right thigh and then come back up to the starting position.  Now do the same thing with your left side and alternate.  Smooth, strong movements. Remember, smooth is fast except for when you want to be really fast",
        "Walk outs.  Start standing in place with feet together. With your legs and back straight, bend at the waist, maintain a tight core as you walk your hands forward until you’re in plank position and then walk your hands until you are to your original standing position",
        "Hip thrust. Lay on the ground with your knees bent and both feet on the ground. Flex your core and thrust your hips up and hold for a second. Lower your hips back down and repeat. Calm down there sparky, this is a much hip thrusting as will happen in this workout"
    ]
};